name: CI Pipeline

on:
  push:
    branches: [ "main", "unstable" ]
  pull_request:
    branches: [ "main", "unstable" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            build/
            kernel
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c', '**/*.asm', '**/*.h', 'Makefile') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib qemu-system-x86 make

      - name: Build kernel
        run: make all

      - name: Run kernel in QEMU (basic test)
        run: |
          make run &
          sleep 5
          killall qemu-system-i386 || true

      - name: Upload kernel artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            kernel
            build/
          retention-days: 1

  lint:
    name: Linting
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Lint Makefile
        run: shellcheck -e SC2006,SC2086 Makefile || true

      - name: Check for trailing whitespace (non-fatal)
        run: |
          if grep -r '[[:blank:]]$' src/; then
            echo "::warning::Trailing whitespace found in source files"
            echo "Found trailing whitespace but continuing..."
          fi

      - name: Check file permissions
        run: |
          if find src/ -type f -not -perm 644 | grep .; then
            echo "::warning::Incorrect file permissions found"
            echo "Found permission issues but continuing..."
          fi

  clang-analyzer:
    name: Clang Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tools gcc-multilib make nasm
      - name: Run Clang Static Analyzer
        run: |
          scan-build make all || true

  coverity-reminder:
    name: Coverity Scan Reminder
    runs-on: ubuntu-latest
    steps:
      - name: Reminder