name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib qemu-system-x86 make

      - name: Build kernel
        run: make all

      - name: Run kernel in QEMU
        run: |
          make run &
          sleep 5
          killall qemu-system-i386 || true

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: |
            kernel
            build/
          retention-days: 1

  lint:
    name: Linting
    runs-on: ubuntu-latest
    continue-on-error: true  # Не останавливать workflow при ошибках линтинга

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Lint Makefile
        run: shellcheck -e SC2006,SC2086 Makefile || true

      - name: Check for trailing whitespace (non-fatal)
        run: |
          if grep -r '[[:blank:]]$' src/; then
            echo "::warning::Trailing whitespace found in source files"
            echo "Found trailing whitespace but continuing..."
          fi

      - name: Check file permissions
        run: |
          if find src/ -type f -not -perm 644 | grep .; then
            echo "::warning::Incorrect file permissions found"
            echo "Found permission issues but continuing..."
          fi