name: Code Linter

on: [push, pull_request]

jobs:
  check-whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for trailing whitespace
        run: |
          git grep -I --files-with-matches -r $'[ \t]$' && exit 1 || exit 0

  check-asm-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate NASM indentation
        run: |
          ! find src/ -name "*.asm" -exec grep -L '^\s*[a-z_][a-z0-9_]*:' {} \;